/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    main_arm_Cube007: THREE.Mesh;
    body_Cube012: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

export default function NekoCat(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/neko.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.main_arm_Cube007.geometry}
        material={materials.Material}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body_Cube012.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("/neko.glb");
